PageAdmin/Models/ViewModel/Start/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PageAdmin.Models.ViewModel
{
    public class LoginViewModel
    {
        [Display(Name = "Användar namn")]
        public string Username { get; set; }

        [Display(Name = "Lösenord")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    }
}

PageAdmin/Controllers/StartController.cs
using PageAdmin.DAL;
using PageAdmin.Models;
using PageAdmin.Models.ViewModel;
using PageAdmin.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PageAdmin.Controllers
{
    public class StartController : Controller
    {
        private AdminUserContext _db = new AdminUserContext();
        // GET: Start
        public ActionResult Index()
        {
            var userData = UserService.GetUserData(string.Empty);
            if(userData == string.Empty)
            {
                return RedirectToAction("Login");
            }
            else
            {
                 return RedirectToAction("Index", "AdminUser");
            }
        }

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LoginValidate(LoginViewModel model)
        {
            var user = _db.AdminUser.Where(x => x.UserName.ToLower() == model.Username.ToLower()).SingleOrDefault();
            if(user != null)
            {
                var saltedPassword = UserService.PasswordHash(user.PasswordSalt, model.Password);
                bool passwordMatch = UserService.ComparePassword(user.Password, saltedPassword);
                if (passwordMatch)
                {
                    
                    HttpContext.Response.Cookies.Add(UserService.AuthCookie(user));
                    HttpContext.Response.Cookies.Add(UserService.SiteCookie(user));
                    return RedirectToAction("Index", "AdminUser");
                }
            }
            ModelState.AddModelError("", "Fel användarnamn eller lösenord.");
            return View("Login");
        }
    }
}

PageAdmin/Views/Start/Index.cshtml
@model PageAdmin.Models.UserViewModel
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

PageAdmin/Views/Start/Login.cshtml
@model PageAdmin.Models.ViewModel.LoginViewModel
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

<article>
    @using (Html.BeginForm("LoginValidate", "Start"))
    {
        @Html.AntiForgeryToken();
    <table>
        <tbody>
            <tr>
                <td>@Html.LabelFor(m => m.Username)</td>
                <td>@Html.TextBoxFor(m => m.Username)</td>
            </tr>
            <tr>
                <td>@Html.LabelFor(m => m.Password)</td>
                <td>@Html.TextBoxFor(m => m.Password)</td>
            </tr>
            <tr>
                <td class="alert">
                    @Html.ValidationSummary()
                </td>
            </tr>
            <tr>
                <td><input type="submit" value="Skicka" /></td>
            </tr>
        </tbody>
    </table>
    }
</article>