PageAdmin/Models/Entity/Site.cs
using System;
using System.Collections;
using System.Collections.Generic;

namespace PageAdmin.Models
{
    public class Site
    {
        public Guid ID { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public bool Active { get; set; }

        public virtual ICollection<AdminUser> Users { get; set; }
    }
}

PageAdmin/Models/ViewModel/AdminUser/UserViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PageAdmin.Models
{
    public class UserViewModel
    {
        public Guid Id { get; set; }

        [Display(Name = "Användarnamn")]
        public string UserName { get; set; }
        
        [Display(Name = "Namn")]
        public string Name { get; set; }

        [Display(Name= "Email")]
        public string Email { get; set; }

        [Display(Name = "Roll")]
        public string Role { get; set; }

        [Display(Name = "Skapad")]
        public DateTime CreateDate { get; set; }

        [Display(Name = "Senast inloggad")]
        public DateTime? LastLogin { get; set; }

        public List<UserViewModel> Users { get; set; }

        public UserViewModel()
        {

        }

        public UserViewModel(AdminUser user)
        {
            Id = user.ID;
            UserName = user.UserName;
            Name = user.FirstName + " " + user.LastName;
            Email = user.Email;
            Role = user.Role.ToString();
            CreateDate = user.CreateDate;
            LastLogin = user.LastLogin;
        }

        public UserViewModel(List<AdminUser> users)
        {
            Users = new List<UserViewModel>();
            foreach(var user in users)
            {
                var m = new UserViewModel(user);
                Users.Add(m);
            }
        }
    }

}

PageAdmin/Models/ViewModel/Site/SiteGridViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PageAdmin.Models.ViewModel
{
    public class SiteGridViewModel
    {
        public Guid ID { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public bool Active { get; set; }
        public List<SiteGridViewModel> Sites { get; set; }


        public SiteGridViewModel()
        {

        }

        public SiteGridViewModel(Site site)
        {
            ID = site.ID;
            Name = site.Name;
            Url = site.Url;
            Active = site.Active;
        }

        public SiteGridViewModel(List<Site> sites)
        {
            Sites = new List<SiteGridViewModel>();
            foreach (var site in sites)
            {
                var s = new SiteGridViewModel(site);
                Sites.Add(s);
            }
        }
    }

}

PageAdmin/Controllers/AdminUserController.cs
using PageAdmin.DAL;
using PageAdmin.Helpers;
using PageAdmin.Models;
using PageAdmin.Models.Enum;
using PageAdmin.Models.ViewModel;
using PageAdmin.Service;
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PageAdmin.Controllers
{
    [CustomAuthorizeAttribute("Admin", "Owner")]
    public class AdminUserController : BaseController
    {
        AdminUserContext _db = new AdminUserContext();

        public ActionResult Index()
        {
            var userID = Guid.Parse(UserService.GetUserData("id"));
            var information = new AdminUserIndexViewModel();
            var user = _db.AdminUser.Find(userID);
            information.Name = user.FirstName + " " + user.LastName;
            information.SiteName = user.Site.Name;
            return View(information);
        }
        
        [HttpPost]
        public ActionResult CreateUser(UserFormViewModel model)
        {
            if (ModelState.IsValid)
            {
                EditUser(model);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult UpdateUser(UserFormViewModel model)
        {
            if (ModelState.IsValid)
            {
                EditUser(model);
            }
            return RedirectToAction("Index");
        }

        public JsonResult DeleteUser(string id)
        {
            Guid delUserID = Guid.Parse(id);
            var delUser = _db.AdminUser.Find(delUserID);
            if(delUser == null)
            {
                return Json("Användare kunde inte tas bort");
            }
            delUser.IsDeleted = true;
            _db.SaveChanges();

            Guid userID = Guid.Parse(UserService.GetUserData("id"));

            var user = _db.AdminUser.Where(x => x.ID == userID).SingleOrDefault();
            if (user == null)
            {
                return Json("Test");
            }


            var sites = user.Site;
            var model = new UserViewModel(sites.Users.Where(x => x.IsDeleted == false).ToList());
            string view = RenderRazorViewToString("_UserGrid", model);
            return Json(view, JsonRequestBehavior.AllowGet);
        }

        public void EditUser(UserFormViewModel model)
        {
            if(model.EditType == EditType.Create)
            {
                var user = new AdminUser(model);
                Guid siteId = Guid.Parse(UserService.GetUserData("siteid"));
                user.Site = _db.Site.Where(x => x.ID == siteId).SingleOrDefault();
                _db.AdminUser.Add(user);
                _db.SaveChanges();
            }
            else if(model.EditType == EditType.Edit)
            {
                var user = _db.AdminUser.Where(x => x.UserName == model.Username).SingleOrDefault();
                if(user == null)
                {
                    ModelState.AddModelError("", "Ingen Användare");
                }
                user.ID = model.ID;

                user.UserName = model.Username;
                if (model.EditType == EditType.Edit && model.Password != null)
                {
                    user.PasswordSalt = UserService.GetSalt();
                    user.Password = UserService.PasswordHash(user.PasswordSalt, model.Password);
                }
                user.CreateDate = DateTime.Now;
                user.Role = model.Role;
                user.FirstName = model.FirstName;
                user.LastName = model.LastName;
                user.Email = model.Email;
                user.Address = model.Address;
                user.ZipCode = model.ZipCode;
                user.City = model.City;
                user.IsDeleted = false;

                _db.SaveChanges();
            }
            else if(model.EditType == EditType.Delete)
            {
                var user = _db.AdminUser.Where(x => x.UserName == model.Username && x.Email == model.Email).SingleOrDefault();
                user.IsDeleted = true;
                _db.AdminUser.Attach(user);
                DbEntityEntry<AdminUser> entry = _db.Entry<AdminUser>(user);
                entry.Property(m => m.IsDeleted).IsModified = true;
                _db.SaveChanges();
            }
        }

        public JsonResult LoadForm(string id)
        {
            UserFormViewModel user = new UserFormViewModel();
            if (id == null)
            {
                user.EditType = EditType.Create;
            }
            else
            {
                Guid UserId = Guid.Parse(id);
                var updateUser = new UserFormViewModel(_db.AdminUser.Where(x => x.ID == UserId).SingleOrDefault());
                updateUser.EditType = EditType.Edit;
                user = updateUser;
            }
            string view = RenderRazorViewToString("_UserForm", user);
            return Json(view, JsonRequestBehavior.AllowGet);
        }

        public JsonResult LoadUserGrid()
        {
            Guid userID = Guid.Parse(UserService.GetUserData("id"));

            var user = _db.AdminUser.Where(x => x.ID == userID).SingleOrDefault();
            if (user == null)
            {
                return Json("Test");
            }


            var sites = user.Site;
            var model = new UserViewModel(sites.Users.Where(x => x.IsDeleted == false).ToList());
            string view = RenderRazorViewToString("_UserGrid", model);
            return Json(view, JsonRequestBehavior.AllowGet);
        }
    }
}

PageAdmin/Controllers/SiteController.cs
using PageAdmin.DAL;
using PageAdmin.Helpers;
using PageAdmin.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PageAdmin.Controllers
{
    [CustomAuthorizeAttribute("Owner", "SuperAdmin")]
    public class SiteController : BaseController
    {

        AdminUserContext _db = new AdminUserContext();
        // GET: Site
        public ActionResult Index()
        {

            return View();
        }

        public JsonResult SiteGrid()
        {
            var sites = _db.Site.ToList();
            var model = new SiteGridViewModel(sites);
            var view = RenderRazorViewToString("_siteGrid", model);
            return Json(view, JsonRequestBehavior.AllowGet);
        }

        public JsonResult SiteForm(string id)
        {
            Guid siteID = Guid.Parse(id);
            var site = new SiteGridViewModel(_db.Site.Find(siteID));
            var view = RenderRazorViewToString("_siteForm", site);
            return Json(view);
        }
    }
}

PageAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.Partial("_menu")
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.10/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Client Scripts/MvcFoolproofJQueryValidation.min.js" type="text/javascript"></script>
    <script src="~/Client Scripts/MvcFoolproofValidation.min.js" type="text/javascript"></script>
    <script src="~/Client Scripts/mvcfoolproof.unobtrusive.min.js"  type="text/javascript"></script>
    

    @RenderSection("Script", false)
</body>
</html>

PageAdmin/Views/Shared/_UserGrid.cshtml
@model PageAdmin.Models.UserViewModel
<table>
    <thead>
        <tr>
            <td>@Html.LabelFor(m => m.UserName)</td>
            <td>@Html.LabelFor(m => m.Name)</td>
            <td>@Html.LabelFor(m => m.Email)</td>
            <td>@Html.LabelFor(m => m.Role)</td>
            <td>@Html.LabelFor(m => m.LastLogin)</td>

        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model.Users)
        {
            @Html.HiddenFor(m => m.Id)
            <tr>
                <td>@user.UserName</td>
                <td>@user.Name</td>
                <td>@user.Email</td>
                <td>@user.Role</td>
                <td>@user.LastLogin</td>
                <td>
                    <input type="button" value="Edit" onclick="EditUser('@user.Id')" />
                    <input type="button" value="Ta bort" onclick="DeleteUser('@user.Id')" />
                </td>
            </tr>
        }
    </tbody>
</table>

PageAdmin/Views/Shared/_menu.cshtml
@Html.ActionLink("Användare","Index", "AdminUser")
@Html.ActionLink("Sidor", "Index", "Site")

PageAdmin/Views/Shared/_siteForm.cshtml
@model PageAdmin.Models.ViewModel.SiteGridViewModel

<article id="SiteForm">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-sm-12">
                @Html.LabelFor(m => m.Name)
            </div>
            <div class="col-md-8 col-sm-12">
                @Html.TextBoxFor(m => m.Name)
            </div>
            <div class="warning col-md-12 col-sm-12">
                @Html.ValidationMessageFor(m => m.Name)
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-sm-12">
                @Html.LabelFor(m => m.Url)
            </div>
            <div class="col-md-8 col-sm-12">
                @Html.TextBoxFor(m => m.Url)
            </div>
            <div class="warning col-md-12 col-sm-12">
                @Html.ValidationMessageFor(m => m.Url)
            </div>
        </div>
        <div class="row">
            <div class="col-md-4 col-sm-12">
                @Html.LabelFor(m => m.Active)
            </div>
            <div class="col-md-8 col-sm-12">
                @Html.CheckBoxFor(m => m.Active)
            </div>
        </div>
    </div>
</article>

PageAdmin/Views/Shared/_siteGrid.cshtml
@model PageAdmin.Models.ViewModel.SiteGridViewModel

<table>
    <tr>
        <td>@Html.LabelFor(m => m.Name)</td>
        <td>@Html.LabelFor(m => m.Url)</td>
    </tr>
    
    @foreach(var site in Model.Sites)
    {
        var activateButton = site.Active ? "AvAktivera" : "Aktivera";
        <tr>
            <td>
                @site.Name
            </td>
            <td>
                @site.Url
            </td>
            <td>
                <button onclick="EditSite('@site.ID')">Edit</button>
                <button onclick="Activatesite('@site.ID')"> @activateButton </button>
            </td>
        </tr>
    }

</table>